### PR TITLE
ghc-arm64.patch: update for ghc-7.8.4

### PR DESCRIPTION
**Pull request by andriytk**
It passes rpmbuild prep stage with this patch on CentOS-7 arm64.

### CODE REVIEW

**Comment by juhp** [comment]
Thanks for this.
Is this also a request to update http://copr.fedorainfracloud.org/coprs/petersen/ghc-7.8.4/ ?
I don't suppose you have tried beyond prep, ie to actually build too?
Any comment on the changes to the other arch's?

**Comment by andriytk** [comment]
I did try, of course, and managed to build it with the following command:

```
rpmbuild --define='ghc_bootstrapping 1' -ba rpmbuild/SPECS/ghc.spec
```

Just FYI: I needed to build ghc-7.8 in order to build ghc-8.0 in order to build ghc-8.4 in order to build Dhall for CentOS-7 Aarch64 platform. It's crazy I know, but I could not find ready rpms anywhere in the net, unfortunately. Currently, I'm building ghc-8.0... Fingers crossed!

> a request to update http://copr.fedorainfracloud.org/coprs/petersen/ghc-7.8.4/ ?

Do you mean to trigger the build of rpms? If that's possible that would be great, yes!

**Comment by andriytk** [comment]
Link to QEMU vm image I'm playing with - https://github.com/andriytk/ghc/releases/tag/centos79arm64. Still fighting with GHC-8.0...

**Comment by andriytk** [comment]
[Here](https://github.com/andriytk/ghc/releases/tag/ghc78cs7arm64) are GHC-7.8 rpms with which I managed to build [GHC-8.0 rpms](https://github.com/andriytk/ghc/releases/tag/ghc80cs7arm64) on CentOS-7.9 Arm64. Building GHC-8.4 now...

**Comment by juhp** [comment]
Thanks!

> Any comment on the changes to the other arch's?

I will ignore this since we don't build sparc32 or ppc32 for epel7 anyway.

**Comment by juhp** [comment]
Merged, thanks!

**Comment by juhp** [comment]
Sadly there is no epel7 aarch64 in Fedora copr

**Comment by andriytk** [comment]
GHC-8.4 rpms for CentOS-7.9 Arm64 - https://github.com/andriytk/ghc/releases/tag/ghc84cs7arm64

**Pull request merged**
